### ISSUE TITLE
question about setup your SBPM project.

### ISSUE THREAD

**Issue by Somiacao** [stefanstaniAIM/IPPR2016#1]
Hello,First introduce my environment.It is jdk1.8.0_181 and mysql is mysql-5.6.41-winx64.I hava ran your mysql script. But I confuse why there is not a database.In addition,I can open the localhost:3000,but it is impossible to login,because it did not correspond to mysql.
I cannot find what and where the problem encountered
Thank you very much if you can solve my problem.

**Comment by geisi93** [comment]
Hi,
please try to use following SQL Setup Script:

```
CREATE SCHEMA 'ippr';
COMMIT;

CREATE SCHEMA 'ippr_security';
COMMIT;

CREATE SCHEMA 'ippr_communicator' ;
COMMIT;

CREATE USER 'ippr'@'localhost' IDENTIFIED BY 'Pa$$w0rd';
GRANT ALL PRIVILEGES ON * . * TO 'ippr'@'localhost';
FLUSH PRIVILEGES;
```
